resolver: lts-16.2

packages:
- coinmetrics
- coinmetrics-all-blockchains
- coinmetrics-binance
- coinmetrics-bitcoin
- coinmetrics-cardano
- coinmetrics-cosmos
- coinmetrics-eos
- coinmetrics-ethereum
- coinmetrics-export
- coinmetrics-grin
- coinmetrics-iota
- coinmetrics-monero
- coinmetrics-monitor
- coinmetrics-nem
- coinmetrics-neo
- coinmetrics-ripple
- coinmetrics-stellar
- coinmetrics-storage
- coinmetrics-tendermint
- coinmetrics-tezos
- coinmetrics-tron
- coinmetrics-waves

extra-deps:
- protobuf-0.2.1.3
- diskhash-0.0.4.0
- avro-0.4.7.0
- git: https://github.com/quyse/hanalytics.git
  commit: dbe294c4c1524268683764c3cd3ec947105359c9
  subdirs:
  - hanalytics-avro
  - hanalytics-base
  - hanalytics-bigquery
  - hanalytics-postgres
